// Copyright (c) 2026 kaislate
// SPDX-License-Identifier: GPL-3.0-or-later

package com.kaislate.veldtplayer.data.playlist.db

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * A user playlist. Rows are owned by the app, not by any [com.kaislate.veldtplayer.data.library.LibrarySource]:
 * a playlist may mix entries from several sources, and survives a source going away entirely.
 *
 * [id] is autogenerated; pass 0 on insert.
 */
@Entity(tableName = "playlists")
data class PlaylistEntity(
    @PrimaryKey(autoGenerate = true) val id: Long,
    val name: String,
    val createdAt: Long,
    val updatedAt: Long,
)
