"""Generates Veldt's adaptive launcher icon (design AB1, "Cream morning", chosen 2026-09-27) as vector drawables.

The design was drawn on the full 108-unit adaptive canvas and previewed through a 90-unit mask; launchers show only
the central 72 units, so every design coordinate is scaled by 0.8 about the centre to keep the chosen look.
Usage: python tools/make_veldt_icon.py <app/src/main/res directory>
"""
import math, os, sys
K = 0.8
def T(x, y): return 54 + (x - 54) * K, 54 + (y - 54) * K
def f(v): return f"{v:.2f}".rstrip('0').rstrip('.')
def circle(cx, cy, r):
    return f"M{f(cx - r)},{f(cy)} a{f(r)},{f(r)} 0 1,0 {f(2 * r)},0 a{f(r)},{f(r)} 0 1,0 {f(-2 * r)},0 z"
def curve(base, amp, freq, phase, dy=0.0):
    pts = []
    x = -13.5
    while x <= 121.5 + 1e-6:
        y = base + amp * math.sin(x / 108 * math.pi * 2 * freq + phase) + dy
        pts.append(T(x, y)); x += 1.0
    return pts
def hill_path(base, amp, freq, phase):
    pts = curve(base, amp, freq, phase)
    return "M" + " L".join(f"{f(x)},{f(y)}" for x, y in pts) + " L108,108 L0,108 z"
def band_path(base, amp, freq, phase, thick):
    top = curve(base, amp, freq, phase); bot = curve(base, amp, freq, phase, thick)
    return "M" + " L".join(f"{f(x)},{f(y)}" for x, y in top) + " L" + " L".join(f"{f(x)},{f(y)}" for x, y in reversed(bot)) + " z"

HILLS = [('#8DB86B', 62, 4.6, 1.2, 0.2), ('#4F8B4E', 69, 4.6, 1.6, 2.4), ('#2E5E33', 77, 4.2, 1.1, 4.4), ('#1C3D22', 85, 3.4, 1.8, 1.0)]
RCX, RCY, RR = 54, 50, 19
cx, cy = T(RCX, RCY); r = RR * K
HEAD = ('<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tools/make_veldt_icon.py (design AB1). Edit the script, not this file. -->\n')

def background():
    y0 = T(0, 10)[1]; y1 = T(0, 70)[1]
    return HEAD + f'''<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <!-- morning sky: cream fading to warm amber toward the horizon -->
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear"
                android:startX="54" android:startY="{f(y0)}"
                android:endX="54" android:endY="{f(y1)}"
                android:startColor="#FFF7EBCB" android:endColor="#FFEEC274"/>
        </aapt:attr>
    </path>
</vector>
'''

def foreground():
    parts = []
    parts.append(f'    <!-- the record, set like a sun -->\n    <path android:fillColor="#1B1B1F" android:pathData="{circle(cx, cy, r)}"/>')
    k = RR * 0.42
    while k < RR - 1.2:
        parts.append(f'    <path android:strokeColor="#3A3A42" android:strokeWidth="{f(0.5 * K)}" android:fillColor="#00000000" android:pathData="{circle(cx, cy, k * K)}"/>')
        k += RR * 0.14
    parts.append(f'    <!-- label (the shared Veldt orange) and spindle hole -->\n    <path android:fillColor="#E07A3A" android:pathData="{circle(cx, cy, RR * 0.30 * K)}"/>')
    parts.append(f'    <path android:fillColor="#1B1B1F" android:pathData="{circle(cx, cy, 1.3 * K)}"/>')
    parts.append('    <!-- the veld: four hill-wave layers, far to near -->')
    for color, base, amp, freq, phase in HILLS:
        parts.append(f'    <path android:fillColor="{color}" android:pathData="{hill_path(base, amp, freq, phase)}"/>')
    return HEAD + '''<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
''' + "\n".join(parts) + "\n</vector>\n"

def monochrome():
    ring = circle(cx, cy, r) + " " + circle(cx, cy, RR * 0.62 * K)
    label = circle(cx, cy, RR * 0.30 * K) + " " + circle(cx, cy, 1.4 * K)
    bands = [band_path(69, 4.6, 1.6, 2.4, 3.2), band_path(77, 4.2, 1.1, 4.4, 3.2)]
    # Themed icons use only this layer's alpha; the record reads as a ring + label, the veld as two hill lines.
    return HEAD + f'''<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd" android:pathData="{ring}"/>
    <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd" android:pathData="{label}"/>
    <path android:fillColor="#FFFFFFFF" android:pathData="{bands[0]}"/>
    <path android:fillColor="#FFFFFFFF" android:pathData="{bands[1]}"/>
</vector>
'''
res = sys.argv[1]
for name, fn in [('ic_launcher_background', background), ('ic_launcher_foreground', foreground), ('ic_launcher_monochrome', monochrome)]:
    open(os.path.join(res, 'drawable', name + '.xml'), 'w', encoding='utf-8', newline='\n').write(fn())
print('written')
